[package]
name = "cohort"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version ="1.5.7", features = ["derive"] }
chrono = "0.4.41"
dotenv = "0.15.0"
serde = { version ="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
